### ISSUE TITLE
Password Reset Errors

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#448]
When attempting to create an account on beta.cordfield.com I am informed that the user ID is already in use.

I then attempt to reset the password but receive an error that the password reset cannot be sent because the 
>"Email address is not verified. The following identities >failed the check in region US-EAST-2: >noreply@cordfield.com, seth_mcknight@tsco.org"

**Comment by CarsonF** [comment]
I wasn't able to reproduce the popup error. If you can reproduce can you capture the error in the response on the network tab?

The real error looks to be that the email is already in use.

**Comment by sethmcknight** [comment]
> ~I wasn't able to reproduce the popup error. If you can reproduce can you capture the error in the response on the network tab?~
> 
> ~The real error looks to be that the email is already in use.~
> 
> Need more coffee. Read the description again. Yeah looks like emails are not fully setup for beta. Will look into that.

Sounds good. Here's your response:

`{"errors":[{"message":"Email address is not verified. The following identities failed the check in region US-EAST-2: noreply@cordfield.com, seth_mcknight@tsco.org","extensions":{"code":"InternalServerError","status":500,"codes":["InternalServerError"],"exception":{"message":"Email address is not verified. The following identities failed the check in region US-EAST-2: noreply@cordfield.com, seth_mcknight@tsco.org","stacktrace":[]}},"locations":[{"line":2,"column":3}],"path":["forgotPassword"]}],"data":null,"extensions":{"tracing":{"version":1,"startTime":"2020-09-15T14:51:19.205Z","endTime":"2020-09-15T14:51:20.273Z","duration":1067224874,"execution":{"resolvers":[{"path":["forgotPassword"],"parentType":"Mutation","fieldName":"forgotPassword","returnType":"Boolean!","startOffset":401544,"duration":973451058}]}}}}
`

**Comment by CarsonF** [comment]
Should be working now @sethmcknight

**Comment by sethmcknight** [comment]
@CarsonF got the password reset email (hooray!)

Followed the link and reset my password

Tried to log in and go this error `Something wasn't right. Try again, or reset password.`

Here's the network response:

`{"errors":[{"message":"Invalid credentials","extensions":{"codes":["Unauthenticated","Client"],"status":401,"code":"Unauthenticated","exception":{"message":"Invalid credentials","stacktrace":["at AuthenticationService.login (components/authentication/authentication.service.ts:163:13)","at AuthenticationResolver.login (components/authentication/authentication.resolver.ts:91:20)"]}},"locations":[{"line":2,"column":3}],"path":["login"]}],"data":null,"extensions":{"tracing":{"version":1,"startTime":"2020-09-15T15:54:23.362Z","endTime":"2020-09-15T15:54:23.391Z","duration":29529929,"execution":{"resolvers":[{"path":["login"],"parentType":"Mutation","fieldName":"login","returnType":"LoginOutput!","startOffset":712859,"duration":25425755}]}}}}
`
